name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
      env:
        TEST_PHONE: ${{ secrets.TEST_PHONE }}
        SEVOTRANSACT_ID: ${{ secrets.SEVOTRANSACT_ID }}
        SEVOTRANSACT_KEY: ${{ secrets.SEVOTRANSACT_KEY }}
        SEVOTRANSACT_ACCOUNT: ${{ secrets.SEVOTRANSACT_ACCOUNT }}
        SEVOTRANSACT_DESCRIPTION: ${{ secrets.SEVOTRANSACT_DESCRIPTION }}
        SEVOTRANSACT_NICKNAME: ${{ secrets.SEVOTRANSACT_NICKNAME }}
        SEVOTRANSACT_PRIMARY_CALLBACK: ${{ secrets.SEVOTRANSACT_PRIMARY_CALLBACK }}
        SEVOTRANSACT_SECONDARY_CALLBACK: ${{ secrets.SEVOTRANSACT_SECONDARY_CALLBACK }}
